functional:
- пользователь имеет возможность зарегистрироваться на сайте
- пользователь имеет возможность авторизоваться на сайте
- пользователь может создать игру
- оба игрока видят друг у друга редактор с кодом
- в игру можно играть с ботом и другом
- созданную игру с другом можно отменить
- игру можно выбрать по уровню сложности 
- задачи даны на русском и английском языках 
- возможность общаться в чате с зарегестрированными пользователями 
- завершенная игра должна быть доступна в записи
- возможность посмотреть предстоящие и завершенные турниры
- пользователь может получать очки
- пользователю доступен его рейтинг за неделю, месяц и за все время
- пользователю доступен рейтинг других пользователей
- пользователь может изменить свое имя и окружение в профиле
non-functional:
- сайт должен быть безопасным и защищать данные пользователя
- сайт должен быть удобным на мобильном устройстве
- сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit: 
- игрок не может редактировать чужой код
- сайт должен быть безопасным и защищать данные пользователей
- сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- сайт должен быть совместим с последними версиями браузеров
